In [1]:
import torch.nn as nn
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
Inputs= np.array([ [73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70],
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')
    
#Targets (Apple , Oranges)
Targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

Inputs= torch.from_numpy(Inputs)
Targets= torch.from_numpy(Targets)


In [3]:
Inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [4]:
Targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [5]:
# Dataset and DataLoader
# Dreate a TensorDataSet
from torch.utils.data import TensorDataset

In [6]:
#Define DataSet
Train_DS= TensorDataset(Inputs, Targets)
Train_DS [:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [7]:
# Create DataLoader
from torch.utils.data import DataLoader

In [8]:
#Define DataLoader
Batch_Size= 5
Train_DL = DataLoader(Train_DS,Batch_Size,shuffle = True)

In [9]:
for xb,yb in Train_DL:
    print (xb)
    print (yb)
    

tensor([[ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.]])
tensor([[118., 132.],
        [ 21.,  38.],
        [103., 119.],
        [ 57.,  69.],
        [ 82., 100.]])
tensor([[ 87., 134.,  58.],
        [ 87., 135.,  57.],
        [ 73.,  67.,  43.],
        [ 91.,  87.,  65.],
        [102.,  43.,  37.]])
tensor([[119., 133.],
        [118., 134.],
        [ 56.,  70.],
        [ 80., 102.],
        [ 22.,  37.]])
tensor([[ 68.,  96.,  71.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  88.,  64.]])
tensor([[104., 118.],
        [ 20.,  38.],
        [102., 120.],
        [ 57.,  69.],
        [ 81., 101.]])


In [10]:
# Define Model
Model = nn.Linear (3,2)
print (Model.weight)
print (Model.bias)

Parameter containing:
tensor([[ 0.3967,  0.5448, -0.3213],
        [-0.4569, -0.4304, -0.1779]], requires_grad=True)
Parameter containing:
tensor([-0.1712, -0.4332], requires_grad=True)


In [11]:
# Parameters
list(Model.parameters())

[Parameter containing:
 tensor([[ 0.3967,  0.5448, -0.3213],
         [-0.4569, -0.4304, -0.1779]], requires_grad=True),
 Parameter containing:
 tensor([-0.1712, -0.4332], requires_grad=True)]

In [12]:
Preds = Model (Inputs)

In [13]:
Preds

tensor([[  51.4730,  -70.2658],
        [  63.3073,  -91.2619],
        [  88.7093, -108.1638],
        [  51.8285,  -72.1188],
        [  57.0116,  -85.7212],
        [  51.3248,  -70.2923],
        [  62.4413,  -91.0094],
        [  88.7847, -108.7986],
        [  51.9767,  -72.0923],
        [  56.2936,  -85.4422],
        [  50.6069,  -70.0133],
        [  63.1592,  -91.2884],
        [  89.5753, -108.4163],
        [  52.5464,  -72.3978],
        [  57.1597,  -85.6947]], grad_fn=<AddmmBackward0>)

In [14]:
# Loss Function
# Import nn.functional
import torch.nn.functional as F

In [15]:
# Define Loss Function
LossFn= F.mse_loss
Loss= LossFn(Model(Inputs),Targets)
print (Loss)

tensor(17296.7793, grad_fn=<MseLossBackward0>)


In [16]:
# Define Optimizer
Opt = torch.optim.SGD (Model.parameters(), lr =1e-5)

In [17]:
# Train the Model Steps
# 1- Generate Predictions
# 2- Calculate the loss
# 3- Compute Gradients w.r.t the weights and biases
# 4- Adjust the weights bu subtraqcting a smaqll quantity proportional to the gradient
# 5- Reset the gradients to zero

In [18]:
# Utility Function to Train the Model
def fit (num_epochs, model, loss_fn,opt, train_dl):
    # Repeat for given number of epochs
    for epoch in range (num_epochs):
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate Predictions
            pred = model(xb)
            
            # 2. Calculate Loss
            loss= loss_fn(pred,yb)
            
            # 3. Compute Gradients
            loss.backward()
            
            # 4. Update Parameters us gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
            
        # Print the Progress
        if (epoch+1 )%10 == 0:
            print ('Epoch [{}/{}]  Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [19]:
fit (100, Model,LossFn,Opt,Train_DL)

Epoch [10/100]  Loss: 462.1088
Epoch [20/100]  Loss: 206.0551
Epoch [30/100]  Loss: 161.5990
Epoch [40/100]  Loss: 207.2862
Epoch [50/100]  Loss: 106.0692
Epoch [60/100]  Loss: 54.7552
Epoch [70/100]  Loss: 11.2783
Epoch [80/100]  Loss: 62.1688
Epoch [90/100]  Loss: 38.2658
Epoch [100/100]  Loss: 50.1504


In [20]:
# Generate predictions
preds = Model(Inputs)
preds

tensor([[ 58.6058,  71.5218],
        [ 77.9574,  98.8286],
        [125.5776, 135.2672],
        [ 29.4656,  44.1537],
        [ 89.6343, 111.6792],
        [ 57.4295,  70.5452],
        [ 76.9574,  98.5275],
        [125.4521, 135.6965],
        [ 30.6419,  45.1303],
        [ 89.8107, 112.3547],
        [ 57.6059,  71.2207],
        [ 76.7810,  97.8521],
        [126.5775, 135.5684],
        [ 29.2892,  43.4782],
        [ 90.8107, 112.6558]], grad_fn=<AddmmBackward0>)

In [21]:
# Compare with targets
Targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])