In [1]:
import numpy as np
import torch

In [2]:
# Input (Temp, Rainfall, Humidity )
inputs= np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37] ,
                  [69, 96, 70]], dtype = 'float32')


In [3]:
# Target (Apples, Oranges)
targets= np.array([[56, 70],
                   [81, 101],
                   [119, 133],
                   [22,37],
                   [103,119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensor
inputs= torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
# Weights and Biases
w = torch.randn(2, 3, requires_grad= True)
b = torch.randn(2, requires_grad= True)
print(w)
print(b)

tensor([[-0.3125, -0.1166,  0.1799],
        [-0.1873,  1.0036,  0.3061]], requires_grad=True)
tensor([ 1.3517, -1.0099], requires_grad=True)


In [6]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [7]:
def model (x):
    return x @ w.t()+ b 
    # @ ==> multiplication in Pytorch
    # .t ==> transpose

In [8]:
# Generate Predictions
preds = model(inputs)
print (preds)

tensor([[-21.5331,  65.7201],
        [-25.8277,  89.8523],
        [-31.0197, 134.9311],
        [-28.8760,  34.3646],
        [-18.8068, 103.8387]], grad_fn=<AddBackward0>)


In [9]:
# Loss Function
# MSE loss
def mse (t1,t2):
    diff = t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [10]:
# Compute Loss
loss= mse(preds, targets)
print (loss)

tensor(5773.7842, grad_fn=<DivBackward0>)


In [11]:
# Compute Gradient
loss.backward()


In [12]:
# Adjust Weights and Biases to reduce the loss
# if a gradient value is positive:
##### inreasing the weight element's value slightly will increase the loss
##### decreasing the weight element's value slightly will decrease the loss
# if a gradient value is negative: 
##### inreasing the weight element's value slightly will decrease the loss
##### decreasing the weight element's value slightly will increase the loss

In [13]:
# Adjust weights and reset gradients
with torch.no_grad():
    w-= w.grad* 1e-5
    b-= b.grad* 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [14]:
print (w)
print (b)

tensor([[-0.2284, -0.0194,  0.2385],
        [-0.1824,  1.0088,  0.3100]], requires_grad=True)
tensor([ 1.3527, -1.0098], requires_grad=True)


In [15]:
#Calculate loss
preds = model (inputs)
loss = mse (preds , targets)
print (loss)

tensor(3952.5417, grad_fn=<DivBackward0>)


In [16]:
# Train the Model using Gradient Descent
# Train for 100 epochs
for i in range (100):
    preds= model (inputs)
    loss = mse (preds, targets)
    loss.backward()
    with torch.no_grad():
        w-= w.grad * 1e-5
        b-= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
        

In [17]:
# Calculate loss
preds = model( inputs)
loss = mse (preds, targets)
print (loss)

tensor(66.0798, grad_fn=<DivBackward0>)


In [18]:
preds


tensor([[ 60.5676,  70.5857],
        [ 83.6456,  96.6914],
        [109.9554, 141.5595],
        [ 39.4526,  39.1849],
        [ 93.9698, 110.7509]], grad_fn=<AddBackward0>)

In [19]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])